<?php

namespace ContainerX8KPus7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FijwxfsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Fijwxfs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Fijwxfs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BlogController::delete' => ['privates', '.service_locator.G5AQjsF', 'get_ServiceLocator_G5AQjsFService', true],
            'App\\Controller\\BlogController::post' => ['privates', '.service_locator.G5AQjsF', 'get_ServiceLocator_G5AQjsFService', true],
            'App\\Controller\\BlogController::postBySlug' => ['privates', '.service_locator.G5AQjsF', 'get_ServiceLocator_G5AQjsFService', true],
            'App\\Controller\\ResetPasswordAction::__invoke' => ['privates', '.service_locator.93Qi50q', 'get_ServiceLocator_93Qi50qService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\BlogController:delete' => ['privates', '.service_locator.G5AQjsF', 'get_ServiceLocator_G5AQjsFService', true],
            'App\\Controller\\BlogController:post' => ['privates', '.service_locator.G5AQjsF', 'get_ServiceLocator_G5AQjsFService', true],
            'App\\Controller\\BlogController:postBySlug' => ['privates', '.service_locator.G5AQjsF', 'get_ServiceLocator_G5AQjsFService', true],
            'App\\Controller\\ResetPasswordAction:__invoke' => ['privates', '.service_locator.93Qi50q', 'get_ServiceLocator_93Qi50qService', true],
            'App\\Controller\\ResetPasswordAction' => ['privates', '.service_locator.93Qi50q', 'get_ServiceLocator_93Qi50qService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\BlogController::delete' => '?',
            'App\\Controller\\BlogController::post' => '?',
            'App\\Controller\\BlogController::postBySlug' => '?',
            'App\\Controller\\ResetPasswordAction::__invoke' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\BlogController:delete' => '?',
            'App\\Controller\\BlogController:post' => '?',
            'App\\Controller\\BlogController:postBySlug' => '?',
            'App\\Controller\\ResetPasswordAction:__invoke' => '?',
            'App\\Controller\\ResetPasswordAction' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
