<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJojiZFb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJojiZFb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJojiZFb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJojiZFb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJojiZFb\App_KernelDevDebugContainer([
    'container.build_hash' => 'JojiZFb',
    'container.build_id' => '40859ce0',
    'container.build_time' => 1605609673,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJojiZFb');
