<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSAVHBOo\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSAVHBOo/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSAVHBOo.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSAVHBOo\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSAVHBOo\App_KernelDevDebugContainer([
    'container.build_hash' => 'SAVHBOo',
    'container.build_id' => 'd09f4595',
    'container.build_time' => 1605046591,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSAVHBOo');
