<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVxKY8up\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVxKY8up/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVxKY8up.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVxKY8up\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVxKY8up\App_KernelDevDebugContainer([
    'container.build_hash' => 'VxKY8up',
    'container.build_id' => '3c534a9a',
    'container.build_time' => 1604514955,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVxKY8up');
