<?php

namespace ContainerXdMX3Jk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordHashSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\PasswordHashSubscriber' shared autowired service.
     *
     * @return \App\EventListener\PasswordHashSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/PasswordHashSubscriber.php';

        return $container->privates['App\\EventListener\\PasswordHashSubscriber'] = new \App\EventListener\PasswordHashSubscriber(($container->services['security.password_encoder'] ?? $container->load('getSecurity_PasswordEncoderService')));
    }
}
