<?php

namespace ContainerXAVzIrx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthoredEntitySubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\AuthoredEntitySubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\AuthoredEntitySubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/AuthoredEntitySubscriber.php';

        return $container->privates['App\\EventSubscriber\\AuthoredEntitySubscriber'] = new \App\EventSubscriber\AuthoredEntitySubscriber(($container->services['security.token_storage'] ?? $container->getSecurity_TokenStorageService()));
    }
}
