<?php

namespace ContainerXAVzIrx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordHashSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventSubscriber\PasswordHashSubscriber' shared autowired service.
     *
     * @return \App\EventSubscriber\PasswordHashSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventSubscriber/PasswordHashSubscriber.php';

        return $container->privates['App\\EventSubscriber\\PasswordHashSubscriber'] = new \App\EventSubscriber\PasswordHashSubscriber(($container->services['security.password_encoder'] ?? $container->load('getSecurity_PasswordEncoderService')));
    }
}
